Bug fixes and improvements
- Now using GNU Wget for recursive downloads, which is fast and does not trigger the PS4 FTP servers' connection bug
- Removed the "multiple downloads" option - no longer necessary
- Several bug fixes and minor improvements

diff --git a/ftpdump b/ftpdump
--- a/ftpdump
+++ b/ftpdump
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Dumps PS4 games via FTP connection over the network.
-# Requires cURL and a PS4 FTP server that supports SELF decryption.
+# Requires cURL, GNU Wget, and a PS4 FTP server that supports SELF decryption.
 # Best results with the FTP payload from https://github.com/hippie68/ps4-ftp.
 # For maximum speed, a gigabit cable connection is recommended.
 # Get the latest script version at https://github.com/hippie68/ftpdump.
@@ -12,8 +12,6 @@
 ip=
 # PS4's FTP port (FTP payload: 1337)
 port=
-# Maximum number of simultaneous downloads
-download_limit=1
 # Beep when done
 beep=false
 # How long to beep, in seconds
@@ -26,12 +24,12 @@ beep_interval=3
 print_usage() {
   cat << EOF
 Usage: ${0##*/} [OPTIONS] HOSTNAME|IP_ADDRESS[:PORT] [OUTPUT_DIRECTORY]
-   Or: ${0##*/} --extract-pfs|--extract-pkg FILE
+   Or: ${0##*/} --extract-pfs|--extract-pkg FILE [OUTPUT_DIRECTORY]
 
 1) Insert a disc and install the game. Optional: visit orbispatches.com
    to download and install a game patch compatible with your firmware.
-2) Start an FTP server. Recommended: https://github.com/hippie68/ps4-ftp.
-3) Press the PS button to leave the browser while keeping the server alive.
+2) Start a PS4 FTP server (recommended: https://github.com/hippie68/ps4-ftp).
+3) Press the PS button to leave the browser.
 4) Run the game.
 5) Run this script.
 
@@ -47,10 +45,6 @@ Options:
   -a, --app         Dump app data.
       --appdb       Dump app.db file and quit.
   -d, --dlc         Dump DLC data.
-      --download-limit NUMBER
-                    Maximum number of simultaneous downloads. Values greater
-                    than 1 mean downloads run asynchronously. Only use this if
-                    the FTP server can handle simultaneous SELF decryptions.
       --debug       Print debug information.
       --debug-pfs   Print debug information while extracting a PFS image file.
       --dump PATH   Dump specified FTP file or directory and quit.
@@ -62,14 +56,10 @@ Options:
   -h, --help        Print usage information.
   -k, --keystone    Dump original keystone.
       --no-decrypt  Do not tell the FTP server to enable SELF decryption.
-      --no-warning  Do not display general usage warnings. Critical script
-                    execution warnings will still be displayed.
   -p, --patch       Dump patch data.
   -s, --sflash      Dump sflash0 file and quit.
       --use-pfs     Instead of downloading files separately, download and
-                    extract the PFS image file. It will take longer, but might
-                    be useful to prevent PS4 FTP servers from crashing, which
-                    eventually will happen when downloading thousands of files.
+                    extract the PFS image file.
   -v, --verbose     Increase cURL's verbosity to see the client/server dialog.
 EOF
 }
@@ -126,7 +116,7 @@ kill_downloads() {
   fi
 }
 
-# Properly stops all ongoing jobs and downloads, then exits the script
+# Properly stops all downloads, then exits the script
 # $1: exit code, $2: optional message
 clean_exit() {
   kill $(jobs -p) 2> /dev/null
@@ -143,11 +133,10 @@ sigint_exit() {
   clean_exit 0 "Script aborted by user."
 }
 
-# Stops the script/job execution, printing an optional error message $1
+# Stops the script execution, printing an optional error message $1
 # $2 being set means it's a critical bug that needs to be reported
 abort() {
   if [[ $1 ]]; then
-    # Print the message
     echo "$1" >&2
     # Log the message in the error log file
     echo "[$(date)] $1" >> "$error_file"
@@ -165,10 +154,8 @@ abort() {
   fi
 }
 
-# Used by the main process in the middle of the script to check if errors
-# occured during jobs
-wait_and_check_for_errors() {
-  wait
+# Used by the main process to check if errors occured during jobs
+check_for_errors() {
   if [[ -e "$error_file" ]]; then
     abort
   fi
@@ -176,19 +163,40 @@ wait_and_check_for_errors() {
 
 # Used by the main process before the script exits, as a final job error check
 check_for_errors_and_exit() {
-  wait_and_check_for_errors
+  wait
+  check_for_errors
   echo "Done."
   exit 0
 }
 
+# Called when cURL encounters an error
 # $1: optional file name
 curl_error() {
   message="cURL reported error $? (see https://curl.se/libcurl/c/libcurl-errors.html)."
   if [[ $1 ]]; then
-    message="\"${1/$root/}\": $message"
+    message="\"${1#$root}\": $message"
   fi
   debug_message "cURL's message: $message"
   abort "$message"
+}
+
+# Called when Wget encounters an error
+# $1: exit code
+wget_error() {
+  local e
+  case $1 in
+    0) e="No problems occured" ;;
+    1) e="Generic error code" ;;
+    2) e="Parse error" ;;
+    3) e="File I/O error" ;;
+    4) e="Network failure" ;;
+    5) e="SSL verification failure" ;;
+    6) e="Username/password authentication failure" ;;
+    7) e="Protocol error" ;;
+    8) e="Server issued an error response" ;;
+    *) e="Unknown error (see https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html" ;;
+  esac
+  abort "Wget reported error $1: $e."
 }
 
 # Portable replacement for GNU realpath
@@ -225,72 +233,53 @@ disable_download_progress() {
 dump_file() {
   local new_file=${1##*/}
 
-  # Abort script if a previous download has failed
-  if [[ -e "$error_file" ]]; then
-    abort 1
-  fi
-
-  # Obey connection limit
-  while [[ $download_jobs_enabled && $(jobs -r | wc -l) -ge "$download_limit" ]]; do
-    wait -n
-  done
-
   echo -e "\e[2K\r$new_file"
   print_download_progress
 
   # Download partial file
   if [[ $2 ]]; then
-    wait # To prevent kill_downloads, below, from killing ongoing downloads
     curl $curl_verbose --silent --ignore-content-length "${1//#/%23}" \
       | dd "$dd_options" skip="$2" count="$3" 2> /dev/null > "$new_file" || \
       curl_error "$1"
     kill_downloads
   # Download full file
   else
-    # Run as job
-    if [[ $download_jobs_enabled ]]; then
-      curl $curl_verbose --silent --ignore-content-length "${1//#/%23}" \
-        > "$new_file" || curl_error "$1" &
-    # Run one at a time
-    else
-      curl $curl_verbose --silent --ignore-content-length "${1//#/%23}" \
-        > "$new_file" || curl_error "$1"
-    fi
+    curl $curl_verbose --silent --ignore-content-length "${1//#/%23}" \
+      > "$new_file" || curl_error "$1"
   fi
 }
 
-# Recursively downloads an FTP directory (this functionality is missing in cURL)
+# Recursively downloads an FTP directory with GNU Wget
+# $1: full directory path; must end with "/"
 dump_dir() {
+  local dir_count=0
   local line
-  local new_dir
+  local i
 
-  while read line; do
-    debug_message "FTP directory entry: $line"
-
-    # Check for known directory listing syntax, while at the same time storing
-    # directory entry values in BASH_REMATCH[] array
-    if [[ ! $line =~ ^(.{10})\ ([0-9]+)\ ([^ ]+[ ]*[^ ]+)\ ([0-9]+)\ ([^ ]+\ +[0-9]+\ [^ ]+)\ (.+) ]]; then
-      abort "Not able to proceed: FTP server uses unknown directory listing." 1
+  # Count number of directories for Wget
+  line=${1#$root}
+  for ((i = 0; i < ${#line}; i++)); do
+    if [[ ${1:$i:1} == "/" && ${1:$((i - 1)):1} != "\\" ]]; then
+      ((dir_count++))
     fi
+  done
 
-    # Recurse directories
-    if [[ $line == d* ]]; then
-      new_dir=${BASH_REMATCH[6]}
-      if [[ $new_dir != . && $new_dir != .. ]]; then # Skip . and .. directories
-        echo -e "\e[2K\r$new_dir/"
+  # Download directory recursively
+  while read -r line; do
+    if [[ $line == *"->"* ]]; then
+      file_name=${line%\"*}
+      file_size=${file_name%]*}
+      file_size=${file_size##*[}
+      file_name=${file_name##*\"}
+      if [[ $file_name != *.listing ]]; then # Ignore Wget's temporary files
+        echo -e "\e[2K\r$file_name"
+        # Update download progress
+        ((downloaded_bytes += file_size))
         print_download_progress
-        mkdir --parents "$new_dir" && cd "$new_dir" || abort
-        dump_dir "$1$new_dir/"
-        cd .. || abort
       fi
-    # Download files
-    elif [[ $line == -* ]]; then
-      ((downloaded_bytes += BASH_REMATCH[4]))
-      dump_file "$1${BASH_REMATCH[6]}"
-    else
-      critical_message "Directory entry neither directory nor file: \"$line\"." >&2
     fi
-  done < <(curl --silent "$1")
+  done < <(wget --cut-dirs $dir_count --no-host-directories --no-verbose \
+    --recursive --level inf "$1" 2>&1 || abort "Wget reported an error.")
 }
 
 # Enables SELF decryption, which the FTP server must support
@@ -301,7 +290,7 @@ enable_decryption() {
     curl -v --silent --quote DECRYPT "$root" 2>&1 \
       | grep "SELF decryption enabled" > /dev/null
     if [[ $? != 0 ]]; then
-      echo "Could not enable decryption. Please try a different FTP server or ignore this by using option --no-decrypt." >&2
+      echo "Could not enable SELF decryption. Please try a different FTP server or ignore this by using option --no-decrypt." >&2
       exit 1
     fi
   fi
@@ -560,8 +549,9 @@ extract_pfs_dir() {
         2) # File
           if [[ $2 -ne $superroot_inode_index ]]; then
             if [[ ! -e "$dirent_filename" ]]; then
+              check_for_errors
               # Wait if currently too many files are being extracted
-              if [[ $(jobs -r | wc -l) -ge 4 ]]; then
+              if [[ $(jobs -r | wc -l) -ge 2 ]]; then
                 wait -n
               fi
               # Extract file in the background
@@ -608,7 +598,8 @@ extract_pfs_image() {
   block_size=$(read_int "$1" 32 4)
   extract_pfs_dir "$(realpath "$1")" $superroot_inode_index
   echo "Waiting for extraction to finish ..."
-  wait_and_check_for_errors
+  wait
+  check_for_errors
 }
 
 # Downloads and extracts PFS image file $1
@@ -653,7 +644,12 @@ error_file="$(pwd)/error_log.txt"
 
 trap sigint_exit SIGINT # To catch CTRL-C
 
-rm "$error_file" 2> /dev/null # Remove old error log file
+# Remove old error log file
+rm "$error_file" 2> /dev/null
+if [[ -e "$error_file" ]]; then
+  echo "Could not remove the old error log file \"$error_file\". Please remove it before starting the script." 2>&1
+  exit 1
+fi
 
 # Get options
 build_args "$@"
@@ -676,27 +672,31 @@ for ((i = 0; i < argc; i++)); do
         ;;
       --debug) debug=1 ;;
       --debug-pfs) debug_pfs=1 ;;
-      --download-limit)
-        if [[ $((++i)) -lt argc ]]; then
-          download_limit=${argv[i]}
-        else
-          echo "Missing argument for option --download-limit." >&2
-          exit 1
-        fi
-        ;;
       --extract-pfs)
+        pfs_extraction_mode=1
         if [[ $((++i)) -lt argc ]]; then
-          extract_pfs_image "${argv[i]}"
-          exit 0
+          if [[ ! $noptc ]]; then
+            non_options[noptc++]=${argv[i]}
+          else
+            echo "First non-option argument needs to follow --extract-pfs." >&2
+            print_usage >&2
+            exit 1
+          fi
         else
           echo "Missing argument for option --extract-pfs." >&2
           exit 1
         fi
         ;;
       --extract-pkg)
+        pkg_extraction_mode=1
         if [[ $((++i)) -lt argc ]]; then
-          extract_pkg "${argv[i]}"
-          exit 0
+          if [[ ! $noptc ]]; then
+            non_options[noptc++]=${argv[i]}
+          else
+            echo "First non-option argument needs to follow --extract-pkg." >&2
+            print_usage >&2
+            exit 1
+          fi
         else
           echo "Missing argument for option --extract-pkg." >&2
           exit 1
@@ -708,7 +708,6 @@ for ((i = 0; i < argc; i++)); do
         ;;
       -k|--keystone) dump_keystone=1 ;;
       --no-decrypt) unset decrypt ;;
-      --no-warning) unset warnings ;;
       -p|--patch|--patch-only) dump_patch=1 ;;
       -s|--sflash|--sflash0) dump_sflash=1 ;;
       --use-pfs) pfs_extraction_enabled=1 ;;
@@ -723,6 +722,49 @@ for ((i = 0; i < argc; i++)); do
   fi
 done
 
+# Set dd options
+dd --version | grep GNU > /dev/null
+if [[ $? == 0 ]]; then
+  debug_message "GNU dd detected - using GNU dd options."
+  dd_options="iflag=skip_bytes,count_bytes" # For GNU dd; much faster
+else
+  debug_message "Non-GNU dd detected - using regular dd options (slow!)."
+  dd_options="ibs=1"
+fi
+
+# Set output directory
+if [[ ${non_options[1]} ]]; then
+  output_dir=$(realpath "${non_options[1]}")
+  debug_message "Using output directory \"$output_dir\"."
+else
+  output_dir=$(realpath .)
+  debug_message "Using current directory as output directory."
+fi
+
+# PFS image file extraction (option --extract-pfs)
+if [[ $pfs_extraction_mode ]]; then
+  pfs_file=$(realpath "${non_options[0]}")
+  if [[ ! -f "$pfs_file" ]]; then
+    echo "File does not exist: \"$pfs_file\"." >&2
+    exit 1
+  fi
+  mkdir --parents "$output_dir" && cd "$output_dir" || abort
+  extract_pfs_image "$pfs_file"
+  exit 0
+fi
+
+# PKG file extraction (option --extract-pkg)
+if [[ $pkg_extraction_mode ]]; then
+  pkg_file=$(realpath "${non_options[0]}")
+  if [[ ! -f "$pkg_file" ]]; then
+    echo "File does not exist: \"$pkg_file\"." >&2
+    exit 1
+  fi
+  mkdir --parents "$output_dir" && cd "$output_dir" || abort
+  extract_pkg "$pkg_file"
+  exit 0
+fi
+
 # Dump everything by default
 if [[ ! $dump_app$dump_patch$dump_dlc$dump_keystone$dump_sflash$dump_appdb$dump_path ]]
 then
@@ -730,22 +772,11 @@ then
   dump_app=1 dump_patch=1 dump_dlc=1
 fi
 
-# Enable jobs when download limit > 1
-if [[ $download_limit -gt 1 ]]; then
-  debug_message "Download limit set to $download_limit - downloads are running asynchronously."
-  warning_message "Asynchronous downloads are enabled. The FTP server must support simultaneous SELF decryptions, otherwise dumps can become corrupted."
-  download_jobs_enabled=1
-else
-  download_limit=1
-  debug_message "Download limit set to $download_limit (default)."
-fi
-
 # Display the current state of all options
 debug_message "Options: dump_app=$dump_app, dump_patch=$dump_patch, \
 dump_dlc=$dump_dlc, dump_keystone=$dump_keystone, dump_sflash=$dump_sflash, \
 dump_appdb=$dump_appdb, dump_path=$dump_path, decrypt=$decrypt, \
 debug=$debug, debug_pfs=$debug_pfs, curl_verbose=$curl_verbose, \
-download_jobs_enabled=$download_jobs_enabled, download_limit=$download_limit, \
 pfs_extraction_enabled=$pfs_extraction_enabled"
 
 # Set FTP prefix
@@ -781,27 +812,10 @@ if curl --head --quote KILL "$root" 2> /dev/null; then
   debug_message "Server has a kill switch, which is great."
   kill_switch=1;
 else
-  debug_message "Server does not have a kill switch - subsequent dumps may become slower each time."
+  warning_message "Server does not have a kill switch - subsequent dumps may become slower each time."
 fi
 
-# Set dd options
-dd --version | grep GNU > /dev/null
-if [[ $? == 0 ]]; then
-  debug_message "GNU dd detected - using GNU dd options (faster)."
-  dd_options="iflag=skip_bytes,count_bytes" # For GNU dd; much faster
-else
-  debug_message "Non-GNU dd detected - using regular dd options (slower)."
-  dd_options="ibs=1"
-fi
-
-# Set output directory
-if [[ ${non_options[1]} ]]; then
-  output_dir=$(realpath "${non_options[1]}")
-else
-  output_dir=$(realpath .)
-fi
-debug_message "Using output directory \"$output_dir\"."
-
+# Create output directory
 mkdir --parents "$output_dir" && cd "$output_dir" || abort
 
 # Single-file dumps  -----------------------------------------------------------
@@ -818,11 +832,11 @@ if [[ $dump_sflash ]]; then
   check_for_errors_and_exit
 fi
 
-# Enable decryption
+# Enable decryption, which might be needed from now on
 if [[ $decrypt ]]; then
   enable_decryption
 else
-  warning_message "SELF decryption not enabled." >&2
+  debug_message "Not telling the server to enable SELF decryption." >&2
 fi
 
 # User-provided file or directory
@@ -879,7 +893,6 @@ if [[ $dump_app ]]; then
   mkdir --parents sce_sys && cd sce_sys || abort
   dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
   dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
-  wait_and_check_for_errors
 
   disable_download_progress
 
@@ -912,7 +925,6 @@ if [[ $dump_patch ]]; then
     mkdir --parents sce_sys && cd sce_sys || abort
     dump_file "$root/System_data/priv/appmeta/$title_id/npbind.dat"
     dump_file "$root/System_data/priv/appmeta/$title_id/nptitle.dat"
-    wait_and_check_for_errors
 
     disable_download_progress
 
